<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Common\xyz.Client.Presentation\xyz.Client.Presentation.csproj" />
    <ProjectReference Include="..\Common\xyz.Client.DataModels\xyz.Client.DataModels.csproj" />
    <ProjectReference Include="..\..\Shared\xyz.Shared\xyz.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Mapster" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="Properties\DesignTimeResources.xaml">
      <ContainsDesignTimeResources>true</ContainsDesignTimeResources>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
